Repository GILAJABI/guide, pull requests merged in 2024-05, with the labels that each got.

#4 feat: 회원 관련 페이지 js / f
  src/main/resources/static/css/member/login.css
  src/main/resources/static/css/member/profile.css
  src/main/resources/static/css/member/signUp.css
  src/main/resources/static/js/member/mbti.js
  src/main/resources/static/js/member/signUp.js
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/signUp.html
Labels: 💡feat, 🛠️fix, 🖥️front

#5 feat: 회원가입 처리 / b
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/dto/MemberDTO.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/resources/static/js/member/mbti.js
  src/main/resources/templates/member/signUp.html
  src/test/java/com/guide/ex/repository/MemberRepositoryTests.java
Labels: 💡feat, 💾back

#9 Post b
  src/main/java/com/guide/ex/config/QuerydslConfig.java
  src/main/java/com/guide/ex/domain/Carrot.java
  src/main/java/com/guide/ex/domain/Comment.java
  src/main/java/com/guide/ex/domain/Join.java
  src/main/java/com/guide/ex/domain/Like.java
  src/main/java/com/guide/ex/domain/Post.java
  src/main/java/com/guide/ex/domain/PostImage.java
  src/main/java/com/guide/ex/domain/Review.java
  src/main/java/com/guide/ex/dto/AllPostDTO.java
  src/main/java/com/guide/ex/dto/BoardImageDTO.java
  src/main/java/com/guide/ex/dto/CarrotPostDTO.java
  src/main/java/com/guide/ex/dto/CommentDTO.java
  src/main/java/com/guide/ex/dto/JoinPostDTO.java
  src/main/java/com/guide/ex/dto/PageRequestDTO.java
  src/main/java/com/guide/ex/dto/PageResponseDTO.java
  src/main/java/com/guide/ex/dto/ReviewPostDTO.java
  src/main/java/com/guide/ex/repository/CarrotRepository.java
  src/main/java/com/guide/ex/repository/CommentRepository.java
  src/main/java/com/guide/ex/repository/ImageRepository.java
  src/main/java/com/guide/ex/repository/JoinRepository.java
  src/main/java/com/guide/ex/repository/LikeRepository.java
  src/main/resources/templates/test/test_location_input.html
  src/test/java/com/guide/ex/repository/PostRepositoryTests.java
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: 💾back, 🖥️front

#11 Member
  src/main/java/com/guide/ex/config/CustomServletConfig.java
  src/main/java/com/guide/ex/controller/MainController.java
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/domain/Member.java
  src/main/java/com/guide/ex/domain/MemberProfile.java
  src/main/java/com/guide/ex/dto/MemberDTO.java
  src/main/java/com/guide/ex/repository/MemberProfileRepository.java
  src/main/java/com/guide/ex/repository/MemberRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/java/com/guide/ex/util/YearAttributeConverter.java
  src/main/resources/static/css/header.css
  src/main/resources/static/css/member/index.css
  src/main/resources/static/css/member/login.css
  src/main/resources/static/css/member/profile.css
  src/main/resources/static/css/member/signUp.css
  src/main/resources/static/image/kakao.png
  src/main/resources/static/image/logo.png
  src/main/resources/static/index.html
  src/main/resources/static/js/member/index.js
  src/main/resources/static/js/member/login.js
  src/main/resources/static/js/member/mbti.js
  src/main/resources/static/js/member/signUp.js
  src/main/resources/templates/include/header.html
  src/main/resources/templates/include/index.html
  src/main/resources/templates/member/index.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/signUp.html
  src/main/resources/templates/member/testLogin.html
  src/test/java/com/guide/ex/repository/MemberProfileRepositoryTests.java
  src/test/java/com/guide/ex/repository/MemberRepositoryTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💡feat, 💾back, 🖥️front

#13 feat: 마이페이지, 타회원정보조회페이지 / f
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/static/image/chat.png
  src/main/resources/static/image/chattingBtn.png
  src/main/resources/static/image/high.png
  src/main/resources/static/image/like.png
  src/main/resources/static/image/post.png
  src/main/resources/static/image/user.png
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
Labels: 💡feat, 🖥️front

#14 Member b
  src/main/java/com/guide/ex/domain/Member.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/test/java/com/guide/ex/repository/MemberRepositoryTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💡feat, 💾back

#15 test: 사진 업로드 테스트(insert)
  build.gradle
  src/main/java/com/guide/ex/controller/ImgController.java
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/controller/test/TestController.java
  src/main/java/com/guide/ex/controller/test/TestRestController.java
  src/main/java/com/guide/ex/domain/MemberProfile.java
  src/main/java/com/guide/ex/dto/MemberProfileDTO.java
  src/main/java/com/guide/ex/repository/MemberProfileRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/test/test_img.html
  src/main/resources/templates/test/test_out_member.html
  src/test/java/com/guide/ex/repository/MemberProfileRepositoryTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: test

#16 build: ModelMapper
  build.gradle
  src/main/java/com/guide/ex/config/RootConfig.java
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💾back

#18 Board b
  src/main/java/com/guide/ex/domain/Comment.java
  src/main/java/com/guide/ex/domain/Post.java
  src/main/java/com/guide/ex/domain/Review.java
  src/main/java/com/guide/ex/dto/AllPostDTO.java
  src/main/java/com/guide/ex/dto/CarrotPostDTO.java
  src/main/java/com/guide/ex/dto/JoinPostDTO.java
  src/main/java/com/guide/ex/dto/ReviewPostDTO.java
  src/main/java/com/guide/ex/dto/SearchDTO.java
  src/main/java/com/guide/ex/repository/ReviewRepository.java
  src/main/java/com/guide/ex/repository/search/AllPostSearch.java
  src/main/java/com/guide/ex/repository/search/AllPostSearchImpl.java
  src/main/java/com/guide/ex/service/PostService.java
  src/main/java/com/guide/ex/service/PostServiceImpl.java
  src/test/java/com/guide/ex/repository/PostRepositoryTests.java
  src/test/java/com/guide/ex/repository/QueryDslTests.java
Labels: 💾back, 📲test

#19 fix: 웹소켓 엔드포인트 재설정 / b
  src/main/java/com/guide/ex/config/WebSocketConfig.java
  src/main/resources/static/js/chat/chatTest.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/room.html
Labels: 🛠️fix, 💾back

#22 Member
  build.gradle
  src/main/java/com/guide/ex/config/RootConfig.java
  src/main/java/com/guide/ex/controller/ImgController.java
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/controller/test/TestController.java
  src/main/java/com/guide/ex/controller/test/TestRestController.java
  src/main/java/com/guide/ex/domain/Member.java
  src/main/java/com/guide/ex/domain/MemberProfile.java
  src/main/java/com/guide/ex/dto/MemberProfileDTO.java
  src/main/java/com/guide/ex/repository/MemberProfileRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/static/image/chat.png
  src/main/resources/static/image/chattingBtn.png
  src/main/resources/static/image/high.png
  src/main/resources/static/image/like.png
  src/main/resources/static/image/post.png
  src/main/resources/static/image/user.png
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/test/test_img.html
  src/main/resources/templates/test/test_out_member.html
  src/test/java/com/guide/ex/repository/MemberProfileRepositoryTests.java
  src/test/java/com/guide/ex/repository/MemberRepositoryTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: 💾back, 🖥️front, 📲test

#23 test: registerTest / b
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💾back, 📲test

#24 fix: 회원 프로필 화면 수정 / f
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/test/test_img.html
Labels: 💾back, 🖥️front, 📲test

#25 test: 회원 정보 test / b
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/domain/member/MemberProfile.java
  src/main/java/com/guide/ex/dto/member/MemberDTO.java
  src/main/java/com/guide/ex/dto/member/MemberProfileDTO.java
  src/main/java/com/guide/ex/repository/member/MemberProfileRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 📲test

#26 Member pf
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/dto/member/MemberInfoDTO.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/testSuccess.html
  src/test/java/com/guide/ex/repository/member/MemberProfileRepositoryTests.java
Labels: 💾back, 📲test

#33 Member b
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/controller/test/TestController.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/domain/member/MemberProfile.java
  src/main/java/com/guide/ex/dto/member/MemberDTO.java
  src/main/java/com/guide/ex/dto/member/MemberProfileDTO.java
  src/main/java/com/guide/ex/repository/member/MemberProfileRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/static/js/member/mbti.js
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/member/profile.html
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💡feat, 🛠️fix, 💾back

#34 feat: 메인페이지 회원관련 기능구현 / f,b
  build.gradle
  src/main/java/com/guide/ex/controller/MainController.java
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/static/css/main.css
  src/main/resources/static/image/carrotBtn.png
  src/main/resources/static/image/joinBtn.png
  src/main/resources/static/image/main.webp
  src/main/resources/static/image/main_pic.webp
  src/main/resources/static/image/pf_example.png
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
Labels: 💾back, 🖥️front

#40 Member
  build.gradle
  src/main/java/com/guide/ex/controller/ImgController.java
  src/main/java/com/guide/ex/controller/MainController.java
  src/main/java/com/guide/ex/controller/MemberController.java
  src/main/java/com/guide/ex/controller/member/MainController.java
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/controller/test/TestController.java
  src/main/java/com/guide/ex/controller/test/TestRestController.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/domain/member/MemberProfile.java
  src/main/java/com/guide/ex/dto/member/MemberDTO.java
  src/main/java/com/guide/ex/dto/member/MemberProfileDTO.java
  src/main/java/com/guide/ex/repository/member/MemberProfileRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/main.css
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/static/css/member/profile.css
  src/main/resources/static/image/carrotBtn.png
  src/main/resources/static/image/joinBtn.png
  src/main/resources/static/image/main.webp
  src/main/resources/static/image/main_pic.webp
  src/main/resources/static/image/pf_example.png
  src/main/resources/static/image/second.png
  src/main/resources/static/image/third.png
  src/main/resources/static/js/member/mbti.js
  src/main/resources/static/js/member/myPageMbti.js
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/signUp.html
  src/main/resources/templates/member/testLogin.html
  src/main/resources/templates/test/test_img.html
  src/test/java/com/guide/ex/repository/member/MemberProfileRepositoryTests.java
  src/test/java/com/guide/ex/repository/member/MemberRepositoryTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💡feat, 🛠️fix, 💾back, 🖥️front, 📲test

#47 fix: 메인 페이지 프로필 css 수정 및 링크 연결 / f,b
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/templates/main.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/member/profileModify.html
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💡feat, 🛠️fix, 🖥️front

#48 Chat b
  src/main/java/com/guide/ex/controller/chat/ChatHtmlController.java
  src/main/java/static/js/chat/ChatMessage.js
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/chat/chat1.js
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/templates/chat/chatList1.html
  src/main/resources/templates/chat/chatRoom1.html
Labels: 💡feat, 💾back

#50 Post f3
  src/main/resources/static/css/post/write.css
  src/main/resources/static/js/post/mapFindLoc.js
  src/main/resources/static/js/post/mepFindLocCloser.js
  src/main/resources/static/js/post/write.js
  src/main/resources/static/js/stompjs/esm6/index.js
  src/main/resources/templates/post/carrotWtire.html
  src/main/resources/templates/post/joinWrite.html
  src/main/resources/templates/post/reviewWrite.html
Labels: 🖥️front

#52 feat: 게시판 등록 / b
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/dto/post/CarrotDTO.java
  src/main/java/com/guide/ex/dto/post/JoinDTO.java
  src/main/java/com/guide/ex/dto/post/PostDTO.java
  src/main/java/com/guide/ex/dto/post/ReviewDTO.java
  src/main/java/com/guide/ex/service/PostService.java
  src/main/java/com/guide/ex/service/PostServiceImpl.java
  src/main/resources/static/js/post/write.js
  src/main/resources/templates/post/carrotWrite.html
  src/main/resources/templates/post/carrotWtire.html
  src/main/resources/templates/post/joinWrite.html
  src/main/resources/templates/post/reviewWrite.html
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: 💾back, 🖥️front, 📲test

#55 feat: commentController, commentRepositoryTests 구현중 / b
  src/main/java/com/guide/ex/controller/post/CommentController.java
  src/main/java/com/guide/ex/dto/post/CommentDTO.java
  src/test/java/com/guide/ex/repository/post/commentRepositoryTests.java
Labels: 💡feat, 💾back

#56 fix: Detail 수정 / f
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/캐럿디테일.. 수정해서 리뷰 디테일로 써.html
Labels: 🛠️fix, 🖥️front

#57 feat: chat table 새로 생성 / b
  src/main/java/com/guide/ex/controller/chat/ChatController.java
  src/main/java/com/guide/ex/controller/chat/ChatHtmlController.java
  src/main/java/com/guide/ex/controller/chat/ChatRoomController.java
  src/main/java/com/guide/ex/domain/chat/ChatMessage.java
  src/main/java/com/guide/ex/domain/chat/ChatRoom.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/dto/chat/ChatRoomDTO.java
  src/main/java/com/guide/ex/repository/chat/ChatRoomRepository.java
  src/main/java/com/guide/ex/service/ChatService.java
  src/main/java/com/guide/ex/service/ChatServiceImpl.java
  src/main/java/com/guide/ex/service/ChattingService.java
  src/main/resources/application.properties
  src/main/resources/static/js/chat/chatList.js
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/member/signUp.html
  src/test/java/com/guide/ex/repository/chat/ChatMessageRepositoryTests.java
  src/test/java/com/guide/ex/repository/chat/ChatRoomRepositoryTests.java
  src/test/java/com/guide/ex/service/ChatServiceTest.java
Labels: 💡feat, 💾back

#60 Chat
  src/main/java/com/guide/ex/controller/chat/ChatController.java
  src/main/java/com/guide/ex/controller/chat/ChatHtmlController.java
  src/main/java/com/guide/ex/controller/chat/ChatRoomController.java
  src/main/java/com/guide/ex/domain/chat/ChatMessage.java
  src/main/java/com/guide/ex/domain/chat/ChatRoom.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/dto/chat/ChatMessageDTO.java
  src/main/java/com/guide/ex/dto/chat/ChatRoomDTO.java
  src/main/java/com/guide/ex/repository/chat/ChatRoomRepository.java
  src/main/java/com/guide/ex/service/ChatService.java
  src/main/java/com/guide/ex/service/ChatServiceImpl.java
  src/main/java/com/guide/ex/service/ChattingService.java
  src/main/java/static/js/chat/ChatMessage.js
  src/main/resources/application.properties
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/chat/chat1.js
  src/main/resources/static/js/chat/chatList.js
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/templates/chat/chatList.html
  src/main/resources/templates/chat/chatList1.html
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/chatRoom1.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/member/signUp.html
  src/test/java/com/guide/ex/repository/chat/ChatMessageRepositoryTests.java
  src/test/java/com/guide/ex/repository/chat/ChatRoomRepositoryTests.java
  src/test/java/com/guide/ex/service/ChatServiceTest.java
Labels: 💡feat, 🛠️fix, 💾back, 🖥️front

#64 fix: 마이페이지, 타회원페이지 / f
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
Labels: 🛠️fix, 🖥️front

#67 test: 내가 쓴 게시글 조회
  src/main/java/com/guide/ex/dto/member/MemberDTO.java
  src/main/java/com/guide/ex/repository/post/PostRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/test/java/com/guide/ex/repository/post/PostInsertTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 📲test

#69 Chat b
  src/main/java/com/guide/ex/GuideApplication.java
  src/main/java/com/guide/ex/controller/chat/ChatController.java
  src/main/java/com/guide/ex/controller/chat/ChatHtmlController.java
  src/main/java/com/guide/ex/controller/chat/ChatPageController.java
  src/main/java/com/guide/ex/controller/chat/ChatRoomController.java
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/domain/chat/ChatMessage.java
  src/main/java/com/guide/ex/domain/chat/ChatRoom.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/dto/chat/ChatMessageDTO.java
  src/main/java/com/guide/ex/dto/chat/ChatRoomDTO.java
  src/main/java/com/guide/ex/service/ChatServiceImpl.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/main.html
  src/main/resources/templates/member/otherPage.html
  src/test/java/com/guide/ex/service/ChatServiceTest.java
Labels: 💡feat, 💾back

#70 test: controller 구현중 / b
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/domain/post/Comment.java
  src/main/resources/static/js/post/comment.js
  src/main/resources/templates/post/carrotDetail.html
Labels: 📲test

#74 Member
  src/main/java/com/guide/ex/controller/member/MemberController.java
  src/main/java/com/guide/ex/dto/member/MemberDTO.java
  src/main/java/com/guide/ex/repository/post/PostRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
  src/test/java/com/guide/ex/repository/post/PostInsertTests.java
  src/test/java/com/guide/ex/service/MemberServiceTests.java
Labels: 💾back

#75 test: controller 구현중 / b
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/resources/static/js/post/comment.js
  src/main/resources/templates/post/carrotDetail.html
Labels: 📲test

#77 Post comment
  src/main/java/com/guide/ex/controller/post/CommentController.java
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/domain/post/Comment.java
  src/main/java/com/guide/ex/dto/post/CommentDTO.java
  src/main/java/com/guide/ex/repository/search/CommentRepository.java
  src/main/java/com/guide/ex/service/CommentServiceImpl.java
  src/main/resources/static/js/post/comment.js
  src/main/resources/templates/post/carrotDetail.html
Labels: 🛠️fix, 💾back

#79 Chat b
  src/main/java/com/guide/ex/controller/chat/ChatController.java
  src/main/java/com/guide/ex/controller/chat/ChatHtmlController.java
  src/main/java/com/guide/ex/controller/chat/ChatRoomController.java
  src/main/java/com/guide/ex/domain/chat/ChatMessage.java
  src/main/java/com/guide/ex/domain/chat/ChatRoom.java
  src/main/java/com/guide/ex/dto/chat/ChatMessageDTO.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/member/otherPage.html
Labels: 💡feat, 🛠️fix, 💾back

#80 test: 채팅리스트 / b
  src/main/java/com/guide/ex/dto/chat/ChatRoomDTO.java
  src/main/java/com/guide/ex/repository/chat/ChatRoomRepository.java
  src/main/java/com/guide/ex/service/ChatService.java
  src/main/java/com/guide/ex/service/ChatServiceImpl.java
  src/test/java/com/guide/ex/repository/chat/ChatRoomRepositoryTests.java
  src/test/java/com/guide/ex/service/ChatServiceTest.java
  src/test/java/com/guide/ex/service/ChatServiceTests.java
Labels: 💾back, 📲test

#82 fix: 게시판 프론트 수정 / f
  src/main/resources/static/css/header.css
  src/main/resources/static/css/post/JoinMain.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/carrotMain.css
  src/main/resources/static/js/post/carrotMain.js
  src/main/resources/templates/include/header.html
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/reviewDetail.html
Labels: 🛠️fix, 🖥️front

#83 fix: 게시판 프론트 수정 / f
  src/main/resources/static/css/post/JoinMain.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/static/css/post/reviewMain.css
  src/main/resources/static/js/post/postMain.js
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/reviewMain.html
Labels: 🛠️fix, 🖥️front

#94 Post f
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
Labels: 🛠️fix, 🖥️front

#99 Post f
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/reviewMain.html
Labels: 🛠️fix, 🖥️front

#102 Post
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/domain/member/Member.java
  src/main/java/com/guide/ex/domain/post/Post.java
  src/main/java/com/guide/ex/repository/post/PostRepository.java
  src/main/java/com/guide/ex/repository/search/AllPostSearch.java
  src/main/java/com/guide/ex/repository/search/AllPostSearchImpl.java
  src/main/java/com/guide/ex/repository/search/CommentRepository.java
  src/main/java/com/guide/ex/service/MemberService.java
  src/main/java/com/guide/ex/service/MemberServiceImpl.java
  src/main/java/com/guide/ex/service/PostService.java
  src/main/java/com/guide/ex/service/PostServiceImpl.java
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/main.html
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/reviewMain.html
Labels: 💡feat, 🛠️fix, 💾back

#104 fix: header 수정 / f
  src/main/resources/static/css/main.css
  src/main/resources/static/image/main.webp
  src/main/resources/static/image/main_pic.webp
  src/main/resources/templates/main.html
Labels: 🛠️fix, 🖥️front

#105 Post f
  src/main/resources/static/css/post/JoinMain.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/carrotMain.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/static/css/post/reviewMain.css
  src/main/resources/static/js/post/commentSession.js
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/reviewMain.html
Labels: 💡feat, 🛠️fix, 🖥️front

#106 feat : 게시판 댓글 순 검색 및 불필요한 코드 정리
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/repository/search/AllPostSearch.java
  src/main/java/com/guide/ex/repository/search/AllPostSearchImpl.java
  src/main/java/com/guide/ex/service/PostServiceImpl.java
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewMain.html
  src/test/java/com/guide/ex/repository/post/PostSearchTests.java
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: 🐞bug, 💡feat, 🛠️fix, 💾back, 🖥️front, 📲test

#107 Post
  src/main/java/com/guide/ex/controller/post/PostController.java
  src/main/java/com/guide/ex/repository/search/AllPostSearch.java
  src/main/java/com/guide/ex/repository/search/AllPostSearchImpl.java
  src/main/java/com/guide/ex/service/PostServiceImpl.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post/JoinMain.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/carrotMain.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/static/css/post/reviewMain.css
  src/main/resources/static/image/main.png
  src/main/resources/static/image/main.webp
  src/main/resources/static/image/main_pic.png
  src/main/resources/static/image/main_pic.webp
  src/main/resources/static/js/post/commentSession.js
  src/main/resources/templates/main.html
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/carrotMain.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/joinMain.html
  src/main/resources/templates/post/reviewDetail.html
  src/main/resources/templates/post/reviewMain.html
  src/test/java/com/guide/ex/repository/post/PostSearchTests.java
  src/test/java/com/guide/ex/service/PostServiceTests.java
Labels: 🛠️fix, 💾back, 🖥️front

#109 Post f
  src/main/resources/static/css/header.css
  src/main/resources/static/css/member/login.css
  src/main/resources/static/css/member/myPage.css
  src/main/resources/static/css/member/otherPage.css
  src/main/resources/static/css/member/profile.css
  src/main/resources/static/css/member/signUp.css
  src/main/resources/static/css/post/JoinMain.css
  src/main/resources/static/css/post/carrotDetail.css
  src/main/resources/static/css/post/carrotMain.css
  src/main/resources/static/css/post/joinDetail.css
  src/main/resources/static/css/post/reviewDetail.css
  src/main/resources/static/css/post/reviewMain.css
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/otherPage.html
  src/main/resources/templates/post/carrotDetail.html
  src/main/resources/templates/post/joinDetail.html
  src/main/resources/templates/post/reviewDetail.html
Labels: 🛠️fix, 🖥️front

#110 Chat
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/chatRoom.html
Labels: 💡feat, 💾back

#111 fix: main 수정 / f
  src/main/resources/static/css/main.css
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
Labels: 🛠️fix, 🖥️front
